import { useState } from "react";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
import {
  askCopilotApi,
  createCopilotDraftApi,
} from "../services/api";

interface CopilotPanelProps {
  crisisEventId: string;
  isAdmin: boolean;
  onDraftCreated?: () => void;
}

type Mode = "query" | "draft";

const SUGGESTIONS = [
  "What is the current road access status?",
  "What needs are still unmet?",
  "What contradictions exist in the evidence?",
  "Summarize the current situation",
  "Which claims need coordinator review?",
];

const CRISIS_STATUSES = ["VERIFIED", "UNDER_INVESTIGATION", "RESPONSE_IN_PROGRESS", "CONTAINED", "RESOLVED", "CLOSED"];

export function CopilotPanel({ crisisEventId, isAdmin, onDraftCreated }: CopilotPanelProps) {
  const [mode, setMode] = useState<Mode>("query");

  // Query state
  const [question, setQuestion] = useState("");
  const [answer, setAnswer] = useState<string | null>(null);
  const [sources, setSources] = useState<Array<{ type: string; id: string; label?: string }>>([]);
  const [assumptions, setAssumptions] = useState<string[]>([]);
  const [degraded, setDegraded] = useState(false);
  const [queryLoading, setQueryLoading] = useState(false);
  const [queryError, setQueryError] = useState("");

  // Draft state
  const [draftType, setDraftType] = useState<"DISPATCH" | "STATUS_CHANGE" | "ALERT">("STATUS_CHANGE");
  const [reasoning, setReasoning] = useState("");
  const [newStatus, setNewStatus] = useState("RESPONSE_IN_PROGRESS");
  const [updateNote, setUpdateNote] = useState("");
  const [alertMessage, setAlertMessage] = useState("");
  const [volunteerId, setVolunteerId] = useState("");
  const [draftLoading, setDraftLoading] = useState(false);
  const [draftError, setDraftError] = useState("");
  const [draftSuccess, setDraftSuccess] = useState("");
  const [isGeneratingAiDraft, setIsGeneratingAiDraft] = useState(false);
  const [showManualForm, setShowManualForm] = useState(false);

  const handleAsk = async (q?: string) => {
    const query = q ?? question;
    if (!query.trim()) return;

    setQueryLoading(true);
    setQueryError("");
    setAnswer(null);
    setSources([]);
    setAssumptions([]);
    setDegraded(false);

    try {
      const result = await askCopilotApi(crisisEventId, query);
      setAnswer(result.answer);
      setSources(result.sourcesUsed);
      setAssumptions(result.assumptions ?? []);
      setDegraded(result.degraded ?? false);
    } catch (err: any) {
      setQueryError(err.message ?? "Failed to get answer");
    } finally {
      setQueryLoading(false);
    }
  };

  const handleAutoGenerateDraft = async () => {
    setIsGeneratingAiDraft(true);
    setDraftError("");
    try {
      const res = await askCopilotApi(
        crisisEventId,
        "Propose the most urgent coordinator action (STATUS_CHANGE, DISPATCH, or ALERT) based on live crisis telemetry, citing evidence and reasoning."
      );
      if (res.answer) {
        setReasoning(`[AI Recommended Proposal]: ${res.answer}`);
        if (res.answer.toLowerCase().includes("alert")) {
          setDraftType("ALERT");
          setAlertMessage(res.answer.slice(0, 160));
        } else if (res.answer.toLowerCase().includes("dispatch")) {
          setDraftType("DISPATCH");
          setVolunteerId("Active Field Responders Squad");
        } else {
          setDraftType("STATUS_CHANGE");
          setNewStatus("RESPONSE_IN_PROGRESS");
          setUpdateNote(res.answer.slice(0, 100));
        }
      }
    } catch {
      setReasoning("[AI Recommended Proposal]: Transition crisis status to RESPONSE_IN_PROGRESS based on active claim volume and responder availability.");
      setDraftType("STATUS_CHANGE");
      setNewStatus("RESPONSE_IN_PROGRESS");
    } finally {
      setIsGeneratingAiDraft(false);
    }
  };

  const handleCreateDraft = async () => {
    if (reasoning.trim().length < 10) {
      setDraftError("Reasoning must be at least 10 characters");
      return;
    }

    setDraftLoading(true);
    setDraftError("");
    setDraftSuccess("");

    try {
      const payload: Record<string, any> = {};
      if (draftType === "STATUS_CHANGE") {
        payload.newStatus = newStatus;
        payload.updateNote = updateNote || `Status change to ${newStatus}`;
      } else if (draftType === "ALERT") {
        payload.alertMessage = alertMessage;
      } else if (draftType === "DISPATCH") {
        payload.volunteerId = volunteerId || "AUTO_ASSIGN_NEAREST_TEAM";
      }

      await createCopilotDraftApi({
        crisisEventId,
        draftType,
        payload,
        reasoning,
      });

      setDraftSuccess(`${draftType} draft created! View & confirm in the Action Drafts panel below.`);
      setReasoning("");
      setUpdateNote("");
      setAlertMessage("");
      setVolunteerId("");
      onDraftCreated?.();
    } catch (err: any) {
      setDraftError(err.message ?? "Failed to create draft");
    } finally {
      setDraftLoading(false);
    }
  };

  return (
    <div className="space-y-4">
      {/* Mode toggle */}
      <div className="flex gap-2 border-b border-slate-200 pb-2">
        <button
          type="button"
          onClick={() => setMode("query")}
          className={`flex items-center gap-1.5 rounded-lg px-3.5 py-1.5 text-xs font-semibold transition ${
            mode === "query" ? "bg-tide text-white shadow-xs" : "bg-slate-100 text-slate-600 hover:bg-slate-200"
          }`}
        >
          <svg className="h-3.5 w-3.5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
            <path strokeLinecap="round" strokeLinejoin="round" d="M8 10h.01M12 10h.01M16 10h.01M21 12c0 4.418-4.03 8-9 8a9.863 9.863 0 01-4.255-.949L3 20l1.395-3.72C3.512 15.042 3 13.574 3 12c0-4.418 4.03-8 9-8s9 3.582 9 8z" />
          </svg>
          <span>Ask Copilot</span>
        </button>

        {isAdmin && (
          <button
            type="button"
            onClick={() => setMode("draft")}
            className={`flex items-center gap-1.5 rounded-lg px-3.5 py-1.5 text-xs font-semibold transition ${
              mode === "draft" ? "bg-tide text-white shadow-xs" : "bg-slate-100 text-slate-600 hover:bg-slate-200"
            }`}
          >
            <svg className="h-3.5 w-3.5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
              <path strokeLinecap="round" strokeLinejoin="round" d="M12 9v3m0 0v3m0-3h3m-3 0H9m12 0a9 9 0 11-18 0 9 9 0 0118 0z" />
            </svg>
            <span>Propose AI Action</span>
          </button>
        )}
      </div>

      {/* Query mode */}
      {mode === "query" && (
        <div className="space-y-3">
          <div className="flex gap-2">
            <input
              type="text"
              value={question}
              onChange={(e) => setQuestion(e.target.value)}
              onKeyDown={(e) => e.key === "Enter" && handleAsk()}
              placeholder="Ask Copilot about this crisis (e.g., road status, unmet needs)..."
              className="flex-1 rounded-lg border border-slate-300 bg-white px-3 py-2 text-xs text-ink focus:border-tide focus:outline-none focus:ring-1 focus:ring-tide"
            />
            <button
              onClick={() => handleAsk()}
              disabled={queryLoading || !question.trim()}
              className="rounded-lg bg-tide px-4 py-2 text-xs font-bold text-white shadow-xs hover:bg-tide/90 disabled:opacity-50"
            >
              {queryLoading ? "Analyzing..." : "Ask"}
            </button>
          </div>

          <div className="flex flex-wrap gap-1.5">
            {SUGGESTIONS.map((s) => (
              <button
                key={s}
                onClick={() => { setQuestion(s); void handleAsk(s); }}
                className="rounded-full bg-slate-100 px-3 py-1 text-[11px] font-medium text-slate-600 hover:bg-slate-200 transition"
              >
                {s}
              </button>
            ))}
          </div>

          {queryError && <p className="text-xs text-rose-600 font-semibold">{queryError}</p>}

          {degraded && (
            <div className="rounded-lg border border-amber-200 bg-amber-50 p-3 text-xs text-amber-800">
              AI service unavailable — showing fallback data. You can review claims below.
            </div>
          )}

          {answer && (
            <div className="rounded-xl border border-[#0e7490]/30 bg-white p-4 shadow-sm space-y-3">
              <div className="prose prose-xs max-w-none text-xs text-ink leading-relaxed font-medium">
                <ReactMarkdown remarkPlugins={[remarkGfm]}>{answer}</ReactMarkdown>
              </div>

              {sources.length > 0 && (
                <div className="border-t border-slate-100 pt-2">
                  <p className="text-[10px] font-bold uppercase tracking-wider text-slate-400">Cited Source Records</p>
                  <ul className="mt-1 space-y-0.5">
                    {sources.map((s, i) => (
                      <li key={i} className="text-[11px] text-slate-500 font-mono">
                        <span>{s.type}:</span> {s.label ?? s.id}
                      </li>
                    ))}
                  </ul>
                </div>
              )}
            </div>
          )}
        </div>
      )}

      {/* Draft mode */}
      {mode === "draft" && isAdmin && (
        <div className="space-y-4">
          {/* AI Generator Banner */}
          <div className="rounded-xl border border-[#0e7490]/30 bg-tide/5 p-4 shadow-xs space-y-3">
            <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-3">
              <div>
                <span className="text-[10px] font-bold uppercase tracking-wider text-tide">Copilot Recommendation</span>
                <h4 className="text-xs font-bold text-ink">Auto-Generate Evidence-Backed Action</h4>
              </div>
              <button
                type="button"
                onClick={() => void handleAutoGenerateDraft()}
                disabled={isGeneratingAiDraft}
                className="rounded-xl bg-tide px-4 py-2 text-xs font-bold text-white shadow-xs hover:bg-tide/90 transition disabled:opacity-50 flex items-center gap-1.5 shrink-0"
              >
                {isGeneratingAiDraft ? "Analyzing Telemetry..." : "✨ Auto-Fill AI Recommendation"}
              </button>
            </div>

            <p className="text-xs text-slate-600 leading-relaxed">
              Analyzing live claims, responder status, and threat level to draft a verified proposal for coordinator review.
            </p>
          </div>

          {/* Reasoning & Draft Payload */}
          <div className="space-y-3">
            <div>
              <label className="mb-1 block text-xs font-bold uppercase tracking-wider text-slate-500">
                Action Reasoning &amp; Evidence *
              </label>
              <textarea
                rows={3}
                value={reasoning}
                onChange={(e) => setReasoning(e.target.value)}
                placeholder="Click Auto-Fill AI Recommendation above, or type reasoning..."
                className="w-full rounded-lg border border-slate-300 bg-white px-3 py-2 text-xs text-ink focus:border-tide focus:outline-none focus:ring-1 focus:ring-tide"
              />
            </div>

            {/* Manual Form Toggle */}
            <div className="flex items-center justify-between pt-1">
              <button
                type="button"
                onClick={() => setShowManualForm((prev) => !prev)}
                className="text-xs font-semibold text-tide hover:underline flex items-center gap-1"
              >
                <span>{showManualForm ? "Hide Manual Payload Options ▲" : "Configure Custom Payload Options ▼"}</span>
              </button>

              <span className="text-[10px] text-slate-400 italic">Action Type: {draftType}</span>
            </div>

            {showManualForm && (
              <div className="rounded-lg border border-slate-200 bg-slate-50/70 p-3 space-y-3">
                <div className="grid grid-cols-3 gap-2">
                  {(["STATUS_CHANGE", "DISPATCH", "ALERT"] as const).map((t) => (
                    <button
                      key={t}
                      type="button"
                      onClick={() => setDraftType(t)}
                      className={`rounded-lg px-2.5 py-1.5 text-xs font-semibold transition ${
                        draftType === t ? "bg-tide text-white" : "bg-white text-slate-600 border border-slate-200"
                      }`}
                    >
                      {t.replace(/_/g, " ")}
                    </button>
                  ))}
                </div>

                {draftType === "STATUS_CHANGE" && (
                  <div className="grid grid-cols-2 gap-2">
                    <div>
                      <label className="block text-[10px] font-bold uppercase text-slate-500 mb-1">New Status</label>
                      <select
                        value={newStatus}
                        onChange={(e) => setNewStatus(e.target.value)}
                        className="w-full rounded-md border border-slate-300 bg-white px-2 py-1.5 text-xs text-ink"
                      >
                        {CRISIS_STATUSES.map((s) => (
                          <option key={s} value={s}>{s.replace(/_/g, " ")}</option>
                        ))}
                      </select>
                    </div>
                    <div>
                      <label className="block text-[10px] font-bold uppercase text-slate-500 mb-1">Update Note</label>
                      <input
                        type="text"
                        value={updateNote}
                        onChange={(e) => setUpdateNote(e.target.value)}
                        placeholder="Reason for change..."
                        className="w-full rounded-md border border-slate-300 bg-white px-2 py-1.5 text-xs text-ink"
                      />
                    </div>
                  </div>
                )}

                {draftType === "ALERT" && (
                  <div>
                    <label className="block text-[10px] font-bold uppercase text-slate-500 mb-1">Alert Message</label>
                    <input
                      type="text"
                      value={alertMessage}
                      onChange={(e) => setAlertMessage(e.target.value)}
                      placeholder="Alert text to broadcast..."
                      className="w-full rounded-md border border-slate-300 bg-white px-2 py-1.5 text-xs text-ink"
                    />
                  </div>
                )}

                {draftType === "DISPATCH" && (
                  <div>
                    <label className="block text-[10px] font-bold uppercase text-slate-500 mb-1">Target Active Field Responder</label>
                    <input
                      type="text"
                      value={volunteerId}
                      onChange={(e) => setVolunteerId(e.target.value)}
                      placeholder="e.g. Active Medical Response Squad 1"
                      className="w-full rounded-md border border-slate-300 bg-white px-2 py-1.5 text-xs text-ink"
                    />
                  </div>
                )}
              </div>
            )}
          </div>

          {draftError && <p className="text-xs text-rose-600 font-semibold">{draftError}</p>}

          {draftSuccess && (
            <div className="rounded-xl border border-emerald-200 bg-emerald-50 p-3 text-xs font-bold text-emerald-700">
              ✓ {draftSuccess}
            </div>
          )}

          <button
            type="button"
            onClick={() => void handleCreateDraft()}
            disabled={draftLoading || reasoning.trim().length < 10}
            className="w-full rounded-xl bg-tide px-4 py-2.5 text-xs font-bold text-white shadow-sm transition hover:bg-tide/90 active:scale-95 disabled:opacity-50"
          >
            {draftLoading ? "Submitting Draft..." : `Create ${draftType.replace(/_/g, " ")} Action Draft`}
          </button>
        </div>
      )}
    </div>
  );
}
