import fs from "node:fs";
import path from "node:path";

import PDFDocument from "pdfkit";
import { prisma } from "../lib/prisma.js";

export async function aggregateCrisisData(crisisId: string) {
  const crisis = await prisma.crisisEvent.findUnique({
    where: { id: crisisId },
    include: {
      reports: {
        include: {
          incidentReport: {
            include: {
              // Assuming reporter is linked via reporterId to User
              // But IncidentReport doesn't have a direct relation to User in schema except via reporterId
            }
          }
        }
      },
      updates: {
        orderBy: { createdAt: "desc" },
        include: {
          updater: true
        }
      },
      reservations: {
        include: {
          resource: true
        }
      },
      volunteerAssignments: {
        include: {
          volunteer: true
        }
      }
    }
  });

  if (!crisis) throw new Error("Crisis not found");

  // Evidence Summary - Find verified evidence posts near the crisis location
  const evidence = await prisma.evidencePost.findMany({
    where: {
      isVerified: true,
      // Simple location check if coords are present, or just some related evidence
      // For now, let's just get verified posts that might be relevant
      // In a real app, we'd use geo-spatial queries or explicit links
    },
    take: 10,
    orderBy: { createdAt: "desc" }
  });

  // OCR data - from SecureFolders linked to this crisis
  const ocrData = await prisma.secureFolder.findMany({
    where: { crisisId },
    include: {
      files: true
    }
  });

  return { crisis, evidence, ocrData };
}

export async function generateNGOReportPDF(
  crisisId: string, 
  adminId: string, 
  manualData?: { 
    assignedVolunteers?: string[]; 
    resources?: { name: string; amount: string }[] 
  }
) {
  const { crisis, evidence, ocrData } = await aggregateCrisisData(crisisId);
  const admin = await prisma.user.findUnique({ where: { id: adminId } });
  
  // Fetch manual volunteer details if provided
  const manualVolunteers = manualData?.assignedVolunteers?.length 
    ? await prisma.user.findMany({
        where: { id: { in: manualData.assignedVolunteers } },
        select: { fullName: true }
      })
    : [];

  const doc = new PDFDocument({ margin: 50, bufferPages: true });
  const filename = `NGO_Report_${crisisId}_${Date.now()}.pdf`;
  const reportsDir = path.resolve(process.cwd(), "uploads", "reports");
  
  if (!fs.existsSync(reportsDir)) {
    fs.mkdirSync(reportsDir, { recursive: true });
  }
  
  const filePath = path.join(reportsDir, filename);
  const stream = fs.createWriteStream(filePath);
  doc.pipe(stream);

  // --- Cover Page ---
  doc.fontSize(25).text("CORE Platform", { align: "center" });
  doc.moveDown();
  doc.fontSize(30).text(`NGO Summary Report: ${crisis.title}`, { align: "center" });
  doc.moveDown(2);
  
  const startDate = crisis.createdAt.toLocaleDateString();
  const endDate = crisis.status === "RESOLVED" || crisis.status === "CLOSED" 
    ? (crisis.updates[0]?.createdAt.toLocaleDateString() || "N/A")
    : "Ongoing";

  doc.fontSize(14).text(`Event Period: ${startDate} - ${endDate}`, { align: "center" });
  doc.text(`Generated Date: ${new Date().toLocaleDateString()}`, { align: "center" });
  doc.text(`Generated By: ${admin?.fullName || "Admin"}`, { align: "center" });
  
  doc.addPage();

  // --- Executive Summary ---
  doc.fontSize(20).text("Executive Summary", { underline: true });
  doc.moveDown();
  doc.fontSize(12).text(crisis.sitRepText || "No situation summary available.");
  doc.moveDown(2);

  // --- Incident Details ---
  doc.fontSize(20).text("Incident Details", { underline: true });
  doc.moveDown();
  doc.fontSize(12).text(`Type: ${crisis.incidentType}`);
  doc.text(`Severity: ${crisis.severityLevel}`);
  doc.text(`Location: ${crisis.locationText}`);
  doc.moveDown();
  doc.fontSize(12).font("Helvetica-Bold").text("Original Reports:");
  doc.font("Helvetica");
  crisis.reports.forEach((r: any, i: number) => {
    doc.text(`${i+1}. ${r.incidentReport.incidentTitle}`);
    doc.text(`   Description: ${r.incidentReport.description}`, { indent: 20 });
  });
  doc.moveDown(2);

  // --- Timeline of Events ---
  doc.addPage();
  doc.fontSize(20).text("Timeline of Events", { underline: true });
  doc.moveDown();
  [...crisis.updates].reverse().forEach((update: any) => {
    doc.fontSize(10).text(`${update.createdAt.toLocaleString()} - Status: ${update.newStatus} (by ${update.updater.fullName})`, { stroke: true });
    doc.fontSize(12).text(update.updateNote || "No notes.", { indent: 20 });
    doc.moveDown();
  });

  // --- Resource Utilization ---
  doc.addPage();
  doc.fontSize(20).text("Resource Utilization", { underline: true });
  doc.moveDown();
  
  if (manualData?.resources && manualData.resources.length > 0) {
    doc.fontSize(14).font("Helvetica-Bold").text("Directly Allocated Resources:");
    doc.font("Helvetica");
    manualData.resources.forEach((res) => {
      doc.fontSize(12).text(`${res.name}: ${res.amount}`);
    });
    doc.moveDown();
  }

  doc.fontSize(14).font("Helvetica-Bold").text("Reservations & Logistics:");
  doc.font("Helvetica");
  if (crisis.reservations.length > 0) {
    crisis.reservations.forEach((res: any) => {
      doc.fontSize(12).text(`${res.resource.name}: ${res.quantity} (${res.status}) - ${res.justification}`);
    });
  } else {
    doc.text("No resource reservations recorded for this crisis.");
  }
  doc.moveDown(2);

  // --- Volunteer Involvement ---
  doc.fontSize(20).text("Volunteer Involvement", { underline: true });
  doc.moveDown();

  if (manualVolunteers.length > 0) {
    doc.fontSize(14).font("Helvetica-Bold").text("Manually Assigned Volunteers:");
    doc.font("Helvetica");
    manualVolunteers.forEach((v) => {
      doc.fontSize(12).text(`- ${v.fullName}`);
    });
    doc.moveDown();
  }

  doc.fontSize(14).font("Helvetica-Bold").text("System Dispatches:");
  doc.font("Helvetica");
  if (crisis.volunteerAssignments.length > 0) {
    crisis.volunteerAssignments.forEach((assign: any) => {
      doc.fontSize(12).text(`${assign.volunteer.fullName}: ${assign.hoursLogged} hours (${assign.status})`);
    });
  } else {
    doc.text("No volunteer assignments recorded.");
  }

  // --- Visual Evidence Summary ---
  if (evidence.length > 0) {
    doc.addPage();
    doc.fontSize(20).text("Visual Evidence Summary", { underline: true });
    doc.moveDown();
    evidence.forEach((post: any) => {
      doc.fontSize(12).text(`${post.title} - ${new Date(post.createdAt).toLocaleDateString()}`);
      doc.fontSize(10).text(post.description, { indent: 20 });
      doc.moveDown();
    });
  }

  // --- Appendix (OCR) ---
  if (ocrData.length > 0) {
    doc.addPage();
    doc.fontSize(20).text("Appendix: Document Data", { underline: true });
    doc.moveDown();
    ocrData.forEach((folder: any) => {
      doc.fontSize(14).text(`Folder: ${folder.name}`);
      folder.files.forEach((item: any) => {
        doc.fontSize(12).text(`- ${item.fileName}`);
        if (item.description) {
          doc.fontSize(10).text(item.description, { indent: 20 });
        }
      });
      doc.moveDown();
    });
  }

  // --- Footer (Page Numbers) ---
  const range = doc.bufferedPageRange();
  for (let i = range.start; i < range.start + range.count; i++) {
    doc.switchToPage(i);
    doc.fontSize(8).text(
      `Page ${i + 1} of ${range.count}`,
      50,
      doc.page.height - 50,
      { align: "center", width: doc.page.width - 100 }
    );
    doc.text(
      "CONFIDENTIAL - CORE Platform NGO Summary Report",
      50,
      doc.page.height - 65,
      { align: "center", width: doc.page.width - 100 }
    );
  }

  doc.end();

  return new Promise((resolve, reject) => {
    stream.on("finish", async () => {
      const report = await prisma.nGOReport.create({
        data: {
          crisisEventId: crisisId,
          generatedById: adminId,
          title: `NGO Report: ${crisis.title}`,
          fileUrl: `/uploads/reports/${filename}`,
          summary: crisis.sitRepText
        }
      });
      resolve(report);
    });
    stream.on("error", reject);
  });
}

export async function listNGOReports(crisisId?: string) {
  return prisma.nGOReport.findMany({
    where: crisisId ? { crisisEventId: crisisId } : {},
    include: {
      crisisEvent: true,
      generatedBy: true
    },
    orderBy: { createdAt: "desc" }
  });
}

export async function getNGOReportById(reportId: string) {
  return prisma.nGOReport.findUnique({
    where: { id: reportId },
    include: {
      crisisEvent: true,
      generatedBy: true
    }
  });
}
