import type { Role } from "@prisma/client";

export type PermissionAction =
  | "SUBMIT_INCIDENT_REPORT"
  | "REGISTER_RESOURCE"
  | "SUBMIT_VOLUNTEER_REVIEW"
  | "SECURE_DOCUMENTATION"
  | "VIEW_DASHBOARD"
  | "SEARCH_VOLUNTEER_DIRECTORY"
  | "UPDATE_CRISIS_STATUS"
  | "MANAGE_RESOURCE_STOCK"
  | "OPT_IN_DISPATCH_SMS"
  | "GENERATE_NGO_REPORT"
  | "RESERVE_RESOURCES"
  | "LOG_VOLUNTEER_HOURS"
  | "VERIFY_VOLUNTEER_TASKS"
  | "ACCESS_LEADERBOARD"
  | "MODERATE_USERS"
  | "ACCESS_ADMIN_PANEL";

const PERMISSIONS: Record<PermissionAction, Role[]> = {
  SUBMIT_INCIDENT_REPORT: ["USER", "VOLUNTEER", "ADMIN"],
  REGISTER_RESOURCE: ["USER", "VOLUNTEER", "ADMIN"],
  SUBMIT_VOLUNTEER_REVIEW: ["USER", "ADMIN"],
  SECURE_DOCUMENTATION: ["USER", "VOLUNTEER", "ADMIN"],
  VIEW_DASHBOARD: ["USER", "VOLUNTEER", "ADMIN"],
  SEARCH_VOLUNTEER_DIRECTORY: ["USER", "VOLUNTEER", "ADMIN"],
  UPDATE_CRISIS_STATUS: ["VOLUNTEER", "ADMIN"],
  MANAGE_RESOURCE_STOCK: ["USER", "VOLUNTEER", "ADMIN"],
  OPT_IN_DISPATCH_SMS: ["VOLUNTEER"],
  GENERATE_NGO_REPORT: ["ADMIN"],
  RESERVE_RESOURCES: ["USER", "VOLUNTEER", "ADMIN"],
  LOG_VOLUNTEER_HOURS: ["VOLUNTEER"],
  VERIFY_VOLUNTEER_TASKS: ["ADMIN"],
  ACCESS_LEADERBOARD: ["USER", "VOLUNTEER", "ADMIN"],
  MODERATE_USERS: ["ADMIN"],
  ACCESS_ADMIN_PANEL: ["ADMIN"]
};

export function can(role: Role, action: PermissionAction): boolean {
  return PERMISSIONS[action].includes(role);
}
